apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: fileupdatestest-component
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/dev-release-team-tenant/fileupdatestest/fileupdatestest-component@sha256:3991f9a4e9594d3f88438e8fedbfb71ff73105f51d7b032aedc6478eadcfb1d9
        name: my-python
        resources: {}
status: {}
